---
# vars file for dfe-azure

## AD user
#ad_user: ""
#ad_password: ""
#
## Azure service principal
#azure_profile: ""
#azure_tenant: ""
#
## Azure subscription
#azure_subscription: ""
#
## Azure location
#azure_location: ""
#

# OpenShift resource group
azure_resource_group: "OpenShiftV3_{{ env }}"

# public keys
azure_deployment_public_keys: []

azure_template_file: "{{ lookup('file', 'roles/dfe-azure/files/template.json') }}"

azure_hostname_prefix: ukdigital

azure_os_choices:
  - publisher: RedHat
    offer: RHEL
    sku: "7.3"
    version: latest
  - publisher: RedHat
    offer: RHEL
    sku: "7-RAW"  # Yes this is in fact 7.4
    version: latest
  - publisher: OpenLogic
    offer: CentOS
    sku: "7.4"
    version: latest

azure_nsg:
  ep:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-80"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "80"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 900
        direction: "Inbound"
    - name: "port-443"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "443"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 800
        direction: "Inbound"
    - name: "port-1194"
      properties:
        protocol: "UDP"
        sourcePortRange: "*"
        destinationPortRange: "1194"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 700
        direction: "Inbound"
  ns:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-53"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "53"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 900
        direction: "Inbound"
  alb:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-80"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "80"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 900
        direction: "Inbound"
    - name: "port-443"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "443"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 800
        direction: "Inbound"
  aom:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-80"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "80"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 990
        direction: "Inbound"
    - name: "port-8443"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "8443"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 980
        direction: "Inbound"
    - name: "port-9090"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "9090"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 970
        direction: "Inbound"
    - name: "port-111"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "111"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 960
        direction: "Inbound"
    - name: "port-1936"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "1936"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 950
        direction: "Inbound"
    - name: "port-2049"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "2049"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 940
        direction: "Inbound"
    - name: "port-2379"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "2379"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 930
        direction: "Inbound"
    - name: "port-2380"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "2380"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 920
        direction: "Inbound"
    - name: "port-4194"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "4194"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 900
        direction: "Inbound"
    - name: "port-8080"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "8080"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 890
        direction: "Inbound"
    - name: "port-10250"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "10250"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 880
        direction: "Inbound"
    - name: "port-20048"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "20048"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 870
        direction: "Inbound"
    - name: "port-50825"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "50825"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 860
        direction: "Inbound"
    - name: "port-53248"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "53248"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 850
        direction: "Inbound"
    - name: "port-4789"
      properties:
        protocol: "UDP"
        sourcePortRange: "*"
        destinationPortRange: "4789"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 840
        direction: "Inbound"
    - name: "port-8053"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "8053"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 830
        direction: "Inbound"
    - name: "port-24224"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "24224"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 820
        direction: "Inbound"
  aon:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-10250"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "10250"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 990
        direction: "Inbound"
    - name: "port-4789"
      properties:
        protocol: "UDP"
        sourcePortRange: "*"
        destinationPortRange: "4789"
        sourceAddressPrefix: "10.100.1.0/24"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 980
        direction: "Inbound"
  ipa:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-53"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "53"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 900
        direction: "Inbound"
    - name: "port-80"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "80"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 800
        direction: "Inbound"
    - name: "port-88"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "88"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 700
        direction: "Inbound"
    - name: "port-389"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "389"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 600
        direction: "Inbound"
    - name: "port-443"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "443"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 500
        direction: "Inbound"
    - name: "port-464"
      properties:
        protocol: "*"
        sourcePortRange: "*"
        destinationPortRange: "464"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 400
        direction: "Inbound"
    - name: "port-636"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "636"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 300
        direction: "Inbound"
    - name: "port-123"
      properties:
        protocol: "UDP"
        sourcePortRange: "*"
        destinationPortRange: "123"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 200
        direction: "Inbound"
  mtr:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
  slb:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
  som:
    - name: "default-allow-ssh"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
  son:
    - name: "port-22-in"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "10.100.0.0/16"
        destinationAddressPrefix: "*"
        access: "Allow"
        priority: 1000
        direction: "Inbound"
    - name: "port-22-out"
      properties:
        protocol: "TCP"
        sourcePortRange: "*"
        destinationPortRange: "22"
        sourceAddressPrefix: "*"
        destinationAddressPrefix: "10.100.0.0/16"
        access: "Allow"
        priority: 900
        direction: "Outbound"

