
- hosts: localhost
  roles:
    - ukdigital-azure

  vars_prompt:
    - name: azure_credential_profile
      prompt: Section in ~/.azure/credentials file to use
      default: "default"
  vars:
    env: dev3
    azure_template_partial: true
    azure_location: "North Europe"
    azure_machine_spec:
      aom2:
        size: Standard_DS1_v2
        os: rhel74
        instances:
          - hostname: "{{ azure_hostname_prefix }}aom21"
            interfaces:
              - subnet: app2subnet
                ipv4: "10.100.2.21"
                public_ip: false
          - hostname: "{{ azure_hostname_prefix }}aom22"
            interfaces:
              - subnet: app2subnet
                ipv4: "10.100.2.22"
                public_ip: false
          - hostname: "{{ azure_hostname_prefix }}aom23"
            interfaces:
              - subnet: app2subnet
                ipv4: "10.100.2.23"
                public_ip: false
        disk_size_gb: 5
      aom3:
        size: Standard_E2s_v3
        os: rhel74
        instances:
          - hostname: "{{ azure_hostname_prefix }}aom31"
            interfaces:
              - subnet: app3subnet
                ipv4: "10.100.3.21"
                public_ip: false
          - hostname: "{{ azure_hostname_prefix }}aom32"
            interfaces:
              - subnet: app3subnet
                ipv4: "10.100.3.22"
                public_ip: false
          - hostname: "{{ azure_hostname_prefix }}aom33"
            interfaces:
              - subnet: app3subnet
                ipv4: "10.100.3.23"
                public_ip: false
        disk_size_gb: 60
      aon2:
        size: Standard_DS1_v2
        os: rhel74
        instances:
          - hostname: "{{ azure_hostname_prefix }}aon21"
            interfaces:
              - subnet: app2subnet
                ipv4: "10.100.2.51"
                public_ip: false
          - hostname: "{{ azure_hostname_prefix }}aon22"
            interfaces:
              - subnet: app2subnet
                ipv4: "10.100.2.52"
                public_ip: false
        disk_size_gb: 5
      aon3:
        size: Standard_E2s_v3
        os: rhel74
        instances:
          - hostname: "{{ azure_hostname_prefix }}aon31"
            interfaces:
              - subnet: app3subnet
                ipv4: "10.100.3.51"
                public_ip: false
          - hostname: "{{ azure_hostname_prefix }}aon32"
            interfaces:
              - subnet: app3subnet
                ipv4: "10.100.3.52"
                public_ip: false
        disk_size_gb: 60
      ipa2:
        size: Standard_DS1_v2
        os: rhel74
        instances:
          - hostname: "{{ azure_hostname_prefix }}ipa21"
            interfaces:
              - subnet: app2subnet
                ipv4: "10.100.2.11"
                public_ip: false
          - hostname: "{{ azure_hostname_prefix }}ipa22"
            interfaces:
              - subnet: app2subnet
                ipv4: "10.100.2.12"
                public_ip: false
        disk_size_gb: 5

    azure_ssh_keys:
      - path: "/home/cloud-user/.ssh/authorized_keys"
        keyData: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDeBUXXick+qa+nAj0KERaKHnJDx07UBrznHAAErHkK7HY+yvvQKtGEkIXQC4mCgCJc1WkUHIJl91Ppv+hIqCyU4O4X18y0jdLs19xCfZemwrndijXKljLlNWa822vaYKvoem9xVkTNrXCVqmDS9KYdhQrVv+rZwkK98eo6Rs2UcTo8obPxsfOpcWvF+Unoun+Ss20tPiGBf6KW1lX63BZkBrpOZ+w8UAH8OzazsQgru1n+aaNVyOlEHRTGTr+pYnvl3BJDy0dZZ72kmq/pzp7vi7Pclcrp9lnoX0UP1NX/J9LmTT+nk5sjNPg9xQ1+Qv1eduVs8oHWtTt+4R1rgFJB ubul@ubul-minty-vbox"
      - path: "/home/cloud-user/.ssh/authorized_keys"
        keyData: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDN29QIMdObT7hSeDcmLNVFa50/pCAZ1Z7tY4D1KHusRL4BPCjVBa6pFVCwH1qNYgO8YaSgwlLHQyMre+ETU00coHMFflJZETeaFspqR75cwhvGvLH/dwvaqDLC3W2ABMGj+0WjIe04IofvJO5KZF9QO3AwpB4CxYtrZhTSS2Oin66lxgrm1Ar2l0EcyHqmllwodcSqubdvSHOUkgSXHDbC0PJinVmPZsS2ZOc6vTDOOIUgdWH/0ACyHk0hL51F65aQyAQ9UKwfBskqro9nfYmziUBKMJVxUR7hQvp7AnmA66Nn3hdECbnrjR7g3hQaLB6NXIhITsTV8NGWP/HWl03Ml05yStpQjaE1SqSLBmZIZxNnbppWXzdJZMICLMlTr20b9eJ6XhvUOdVCUBIwvOBJqH5vC+ZYLMRT9DKmQcoYMIYizz/mgouR4imZIAvEBCAnjU0Zt0SScKS6GB+PNkJq1MPPcWnEjhwOVrW6LqXmH0uKxegJNEBORTqcBuM7bcFKH7A5hjpoN8MvzCK6ooYmqQ4MfI52nZK4EImQI7r3ntJigX7DcfFRd36/t0JjJuli1CayZbAcFxZlEqQfCXxGfeswh3w9sTYvkoaFcq5ynoeBI4CiUMOLLdtSa63az8Nsq0G5M7vm9z7L84hZLSK6Hyzf2g/aQNpha1azkITDNw== jcook"
      - path: "/home/cloud-user/.ssh/authorized_keys"
        keyData: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDphSbKNCdwE38fvJURIwZU3jj/5KglOQzgxPxbYg4yTHoChNq/4pgHY3RqSdBiIWSTTPBYNXqvDQDHGCTEtMpas2N4eMxmlhaArRZKKC8xPBGzJrhZ3Q3Eyha0x92wqQ7CkFzM77THwNXm/+YEH3FUdl+YJif5uBBxuLqQ5GeoohtmYaxhUR/CCakDYbxIBXAt2wv/ud2MgwH2I/9oi7aBFgoKTMSX6rxAskEMpq6MtwOtnfSWgfSBMVDAk+GK3TQF0msPmnca2+vj4vBl0ufPFRTTL3uaoKWbWOflCPl65jx2sfC1VaspgEBI9XqrPN/cmmLYac/855XmunIqFcz+ndS+Gpwa7KAGKe2q5aTuEPiabC1rSyckOrUTCL9wrB3TVjW85ry3Ct8GuU8Qz32qqqiKODofwOmC4nh8Q6/NWP1KjS92o6fVmueTqJzfo5I2Cf3qV6qHTSsLR03X1W1c2q0o5XHyOaJjf0XMhOk6cG8MIxC2ZHQArBfHbex+MWXdFDvK79tcsixuudAB+jT5bsnXOEw8gjLh9aok5eqZ7bBQIFyygnChN6yntV/kwyts3gwM/Zd/PAj7B8vIBaxfRu8wyA9TK0sNCnbcTZrn2jQuYLxdxMCXvHvGFfJnGDER9nT/BsyNEBOUCueGoBxAeK8dDv3GSCDtfe6JW3eqrQ== nigel@Nigels-MBP"


