
- name: Create main network
  azure_rm_virtualnetwork:
    ad_user: "{{ ad_user }}"
    password: "{{ ad_password }}"
    subscription_id: "{{ azure_subscription }}"
    location: "{{ azure_location }}"
    resource_group: "{{ azure_resource_group }}"
    tenant: "{{ azure_tenant_id }}"
    address_prefixes_cidr: "10.100.0.0/16"
    name: main

- name: Create app1subnet subnet
  azure_rm_subnet:
    ad_user: "{{ ad_user }}"
    password: "{{ ad_password }}"
    subscription_id: "{{ azure_subscription }}"
    resource_group: "{{ azure_resource_group }}"
    tenant: "{{ azure_tenant_id }}"
    name: app1subnet
    virtual_network_name: main
    address_prefix_cidr: "10.100.1.0/24"

- name: Create mgmt1subnet subnet
  azure_rm_subnet:
    ad_user: "{{ ad_user }}"
    password: "{{ ad_password }}"
    subscription_id: "{{ azure_subscription }}"
    resource_group: "{{ azure_resource_group }}"
    tenant: "{{ azure_tenant_id }}"
    name: mgmt1subnet
    virtual_network_name: main
    address_prefix_cidr: "10.100.100.0/24"

- name: Create svc1subnet subnet
  azure_rm_subnet:
    ad_user: "{{ ad_user }}"
    password: "{{ ad_password }}"
    subscription_id: "{{ azure_subscription }}"
    resource_group: "{{ azure_resource_group }}"
    tenant: "{{ azure_tenant_id }}"
    name: svc1subnet
    virtual_network_name: main
    address_prefix_cidr: "10.100.20.0/24"

- name: Create dmz1subnet subnet
  azure_rm_subnet:
    ad_user: "{{ ad_user }}"
    password: "{{ ad_password }}"
    subscription_id: "{{ azure_subscription }}"
    resource_group: "{{ azure_resource_group }}"
    tenant: "{{ azure_tenant_id }}"
    name: dmz1subnet
    virtual_network_name: main
    address_prefix_cidr: "10.100.254.0/24"

- name: Create mtr network
  azure_rm_virtualnetwork:
    ad_user: "{{ ad_user }}"
    password: "{{ ad_password }}"
    subscription_id: "{{ azure_subscription }}"
    location: "{{ azure_location }}"
    resource_group: "{{ azure_resource_group }}"
    tenant: "{{ azure_tenant_id }}"
    address_prefixes_cidr: "172.17.1.0/24"  # TODO: WHY?
    name: mtr

- name: Create mtr1subnet subnet
  azure_rm_subnet:
    ad_user: "{{ ad_user }}"
    password: "{{ ad_password }}"
    subscription_id: "{{ azure_subscription }}"
    resource_group: "{{ azure_resource_group }}"
    tenant: "{{ azure_tenant_id }}"
    name: mtr1subnet
    virtual_network_name: mtr
    address_prefix_cidr: "172.17.1.0/24"

# TODO: There seems to be no azure module for vnet peering


## Peer VNet1 to VNet2.
#az network vnet peering create \
#  --name myVnet1ToMyVnet2 \
#  --resource-group $rgName \
#  --vnet-name myVnet1 \
#  --remote-vnet-id $vnet2Id \
#  --allow-vnet-access