---

#- name: Collect public keys
#  set_fact:
#    azure_deployment_public_keys: "{{ azure_deployment_public_keys + '\n' + lookup('file', item) }}"
#  with_fileglob:
#    - ../files/*.pub

# NOTE: The azure ssh_public_keys performs validation on singular public keys so the concatenation plan is not good
# So here it goes plan B create their list variable from variable amount of files

- name: Collect public keys
  set_fact:
    azure_deployment_public_keys: "{{ azure_deployment_public_keys + [{'path': '/home/cloud-user/.ssh/authorized_keys', 'key_data': lookup('file', item) }] }}"
  with_fileglob:
    - ../files/*.pub

- name: Check the authorized keys file
  debug:
    var: azure_deployment_public_keys
#
#- name: Write it to a file
#  copy:
#    content: "{{ azure_deployment_public_keys }}"
#    dest: roles/dfe-azure/files/authorized_keys

# TODO: Decide if network peering or VPN between them

