---

- name: Rendering azure resource template
  set_fact:
    azure_rendered_template: "{{ lookup('template', 'templates/template.json.j2') }}"
  tags:
    - render

#- name: Also to file
#  template:
#    src: "templates/template.json.j2"
#    dest: "./azuretemplate.json"
#
#- name: look at template
#  debug:
#    msg: "{{ azure_rendered_template }}"

- name: Deploying template in {{ azure_resource_group }}
  azure_rm_deployment:
    deployment_name: "estate_{{ ansible_date_time.iso8601_basic_short }}"
    ad_user: "{{ ad_user }}"
    password: "{{ ad_password }}"
    subscription_id: "{{ azure_subscription }}"
    location: "{{ azure_location }}"
    resource_group: "{{ azure_resource_group }}"
    tenant: "{{ azure_tenant_id }}"
    template: "{{ azure_rendered_template }}"
    parameters: {}
    deployment_mode: complete
  tags:
    - deploy


