---

- name: Deploying template in {{ azure_resource_group }}
  azure_rm_deployment:
    ad_user: "{{ ad_user }}"
    password: "{{ ad_password }}"
    subscription_id: "{{ azure_subscription }}"
    location: "{{ azure_location }}"
    resource_group: "{{ azure_resource_group }}"
    tenant: "{{ azure_tenant_id }}"
    template: "{{ azure_template_file }}"
    parameters: {}
    deployment_mode: complete

